/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "tertiary-container": "#70706c",
        "primary-container": "#e2001a",
        surface: "#fcf9f8",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "on-surface": "#1c1b1b",
        "on-secondary": "#ffffff",
        "surface-container": "#f0eded",
        "outline-variant": "#e8bcb7",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1c1b1b",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#410002",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed": "#ffdad6",
        "surface-variant": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "on-primary-fixed-variant": "#93000d",
        error: "#ba1a1a",
        "secondary-container": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#f7f5ef",
        "tertiary-fixed": "#e4e2dd",
        "on-error-container": "#93000a",
        "surface-tint": "#c00014",
        "secondary-fixed-dim": "#c6c6c6",
        "tertiary-fixed-dim": "#c8c6c1",
        "on-surface-variant": "#5e3f3b",
        secondary: "#5e5e5e",
        "on-secondary-container": "#646464",
        tertiary: "#585854",
        "surface-container-high": "#eae7e7",
        "on-tertiary-fixed-variant": "#474743",
        background: "#fcf9f8",
        "inverse-primary": "#ffb4ab",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed-variant": "#474747",
        "inverse-surface": "#313030",
        primary: "#b40012",
        "on-secondary-fixed": "#1b1b1b",
        "on-tertiary-fixed": "#1b1c19",
        "primary-fixed-dim": "#ffb4ab",
        outline: "#936e6a",
        "on-primary-container": "#fff3f1",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "16px",
        "margin-desktop": "64px",
        "stack-xl": "120px",
        gutter: "24px",
        "stack-lg": "64px",
        "stack-md": "32px",
      },
      fontFamily: {
        "utility-sm": ["Archivo Narrow", "sans-serif"],
        "utility-bold": ["Archivo Narrow", "sans-serif"],
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "body-lg": ["Archivo Narrow", "sans-serif"],
        "display-sm": ["Bodoni Moda", "serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "body-md": ["Archivo Narrow", "sans-serif"],
      },
      fontSize: {
        "utility-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "utility-bold": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "display-lg": [
          "84px",
          { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-sm": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
